package org.PracticaEsfe.Dominio;

import java.sql.Date; // Importa java.sql.Date para los campos de fecha

/**
 * Represents a loan entity in the domain layer.
 * This class holds the attributes of a loan, such as ID, user ID, book ID,
 * loan date, and return date.
 */
public class Prestamo {
    private int id;
    private int idUsuario;
    private int idLibro;
    private Date fechaPrestamo;
    private Date fechaDevolucion; // Can be null if the book has not yet been returned

    /**
     * Default constructor for creating a new Prestamo object without initial values.
     */
    public Prestamo() {
    }

    /**
     * Parameterized constructor for creating a new Prestamo object with all values,
     * including an existing ID (useful when retrieving from DB).
     *
     * @param id The unique identifier for the loan.
     * @param idUsuario The ID of the user who took out the loan.
     * @param idLibro The ID of the book that was loaned.
     * @param fechaPrestamo The date the loan was made.
     * @param fechaDevolucion The date the book was returned (can be null).
     */
    public Prestamo(int id, int idUsuario, int idLibro, Date fechaPrestamo, Date fechaDevolucion) {
        this.id = id;
        this.idUsuario = idUsuario;
        this.idLibro = idLibro;
        this.fechaPrestamo = fechaPrestamo;
        this.fechaDevolucion = fechaDevolucion;
    }

    /**
     * Parameterized constructor for creating a new Prestamo object without an ID
     * (useful for new loans where the ID is auto-generated by the database).
     *
     * @param idUsuario The ID of the user who took out the loan.
     * @param idLibro The ID of the book that was loaned.
     * @param fechaPrestamo The date the loan was made.
     * @param fechaDevolucion The date the book was returned (can be null).
     */
    public Prestamo(int idUsuario, int idLibro, Date fechaPrestamo, Date fechaDevolucion) {
        this.idUsuario = idUsuario;
        this.idLibro = idLibro;
        this.fechaPrestamo = fechaPrestamo;
        this.fechaDevolucion = fechaDevolucion;
    }

    // --- Getters ---
    public int getId() {
        return id;
    }

    public int getIdUsuario() {
        return idUsuario;
    }

    public int getIdLibro() {
        return idLibro;
    }

    public Date getFechaPrestamo() {
        return fechaPrestamo;
    }

    public Date getFechaDevolucion() {
        return fechaDevolucion;
    }

    // --- Setters ---
    public void setId(int id) {
        this.id = id;
    }

    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }

    public void setIdLibro(int idLibro) {
        this.idLibro = idLibro;
    }

    public void setFechaPrestamo(Date fechaPrestamo) {
        this.fechaPrestamo = fechaPrestamo;
    }

    public void setFechaDevolucion(Date fechaDevolucion) {
        this.fechaDevolucion = fechaDevolucion;
    }

    /**
     * Provides a string representation of the Prestamo object for debugging.
     *
     * @return A string containing the loan's ID, user ID, book ID, loan date, and return date.
     */
    @Override
    public String toString() {
        return "Prestamo{" +
                "id=" + id +
                ", idUsuario=" + idUsuario +
                ", idLibro=" + idLibro +
                ", fechaPrestamo=" + fechaPrestamo +
                ", fechaDevolucion=" + fechaDevolucion +
                '}';
    }
}